# Generated by Django 4.1.1 on 2022-10-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
