# Generated by Django 4.1.1 on 2022-10-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_order_id_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
