# Generated by Django 4.1.1 on 2022-11-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='sub_county',
        ),
    ]
