# Generated by Django 4.1.1 on 2022-11-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_deliveryaddress_sub_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
