# Generated by Django 4.1.1 on 2022-11-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_customer_deliveryaddress_customer_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
