# Generated by Django 4.1.1 on 2022-11-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_deliveryaddress_order_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='phone_number',
        ),
    ]
