# Generated by Django 4.1.1 on 2022-11-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
