# Generated by Django 4.1.1 on 2022-11-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_customer_deliveryaddress_customer_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
