# Generated by Django 4.1.1 on 2022-10-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wakulima',
            fields=[
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Id_Number', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=40)),
                ('Phone_Number', models.CharField(max_length=20)),
                ('Farm_size', models.CharField(max_length=10)),
                ('Farm_Number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Crop_Name', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
