# Generated by Django 4.1.1 on 2022-10-14 10:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_wakulima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wakulima',
            name='Email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='wakulima',
            name='Phone_Number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None),
        ),
    ]
