# Generated by Django 4.1.1 on 2022-11-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_alter_wakulima_email_alter_wakulima_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('content', models.TextField(max_length=1000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
