# Generated by Django 4.1.1 on 2022-11-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
