# Generated by Django 4.1.1 on 2022-11-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0008_alter_post_body_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subcounty', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('subject', models.TextField()),
            ],
        ),
    ]
