# Generated by Django 4.1.1 on 2022-11-12 02:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0011_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
